services:
  - type: web
    name: playwright-proxy
    env: node
    buildCommand: |
      npm install
      npx playwright install --with-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
